

project_id = "xdpcxiouirwcfwybyxmr"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:8080"
additional_redirect_urls = ["http://localhost:3000", "http://localhost:8080"]
jwt_expiry = 3600
enable_signup = true
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

[functions.process-recording]
verify_jwt = false

[functions.chat-with-recording]
verify_jwt = false

[functions.reprocess-coaching]
verify_jwt = false

[storage]
enabled = true
file_size_limit = "50MiB"
