name: Admin Cypress Smoke

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build
        env:
          CI: true
      
      - name: Run Cypress smoke tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run preview
          wait-on: 'http://localhost:5173'
          wait-on-timeout: 120
          spec: cypress/e2e/admin-smoke.cy.ts
          browser: chrome
          headless: true
          record: false
          # Add environment variables for CI
          env: |
            CI=true
            NODE_ENV=test
